version: '3.8'

services:
  postgres_container:
    image: postgres:13
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: student_api_db
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network

  server:
    container_name: server_container
    depends_on:
      - postgres_container
    build:
      context: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - ./app/node_modules
    networks:
      - app_network

  client:
    container_name: client_container
    build:
      context: ./client
    ports:
      - '5173:5173'
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db:
